### PR TITLE
fix(core): fix nickname error, close #7

### LINKED ISSUE #7: Bug: nickname
https://github.com/koishijs/koishi-plugin-dialogue/blob/f4986708cab64285c7113b9a4e5f6a35e42fab11/packages/core/src/command.ts#L71

### PR DESCRIPTION
**Pull request by jiajiu123**
当bot的nickname未设置时后台报错
2023-03-17 00:04:15 [W] command help teach
TypeError: Cannot read properties of undefined (reading '0')
at cheatSheet (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:354:32)
at _Command._usage (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:418:173)
at showHelp (/koishi/node_modules/@koishijs/plugin-help/lib/index.js:265:85)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1648:14)
at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1663:22)
at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2221:22
at async Session2.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2104:14)
at async Lifecycle.serial (/koishi/node_modules/cordis/lib/index.cjs:107:22)
at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1640:22)
此处增加了一层判断，当nickname未设置时默认使用bot的qq昵称

### CODE REVIEW

File: packages/core/src/command.ts [hunk 1]
```diff
@@ -67,11 +67,15 @@ const cheatSheet = (session: Dialogue.Session, config: Dialogue.Config) => {
...
+　$a：@说话人`,470);
+if (session.app.config.nickname != null) {
+  output.add(`　$m：@${session.app.config.nickname[0]}`, 460);
+} else {
+  output.add(`　$m：@${session.bot.username}`, 460);
+}
+  output.add(`　$s：说话人的名字
 　\$()：指令插值
-　\${}：表达式插值`, 0)
+　\${}：表达式插值`, 0);
```
Comment (shigma) [inline packages/core/src/command.ts:78]: 请不要修改无关的部分。

这里的 diff 可以只有一行：

```diff
- session.app.config.nickname[0]
+ session.app.config.nickname?.[0] ?? session.bot.username
```

**Review by shigma — CHANGES_REQUESTED** [review]

**Comment by Anillc** [comment]
应该比这还要早很多，是个非常久远的 bug 了（
